### ISSUE TITLE
results!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [ilyakoloskov/iTunes-Vue#1]
hello dude!please I am begging you could you increase unlimited results?

**Comment by ilyakoloskov** [comment]
> hello dude!please I am begging you could you increase unlimited results?

Hi dude, can't figure out what to increase?

**Comment by KENPOKASMMA1982** [comment]
my friend please help me  ERROR  Failed to compile with 1 error                                                                                                           9:53:08 μ.μ.

This relative module was not found:

* ./IAlbumsRow.vue in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/ISection/ISection.vue?vue&type=script&lang=js

**Comment by ilyakoloskov** [comment]
> my friend please help me ERROR Failed to compile with 1 error 9:53:08 μ.μ.
> 
> This relative module was not found:
> 
> * ./IAlbumsRow.vue in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader-v16/dist??ref--1-1!./src/components/ISection/ISection.vue?vue&type=script&lang=js

Man, sorry for the long answer, fixed everything, try

**Comment by KENPOKASMMA1982** [comment]
MY FRIEND I CANT SEARCH SONG AND ALBUMS WHY???
